### ISSUE TITLE
Reorder models 

### ISSUE THREAD

**Issue by robbertstevens** [krukas/Mage2Gen#57] opened 2017-02-08 09:34 UTC
When I make a new model I like to add attributes that have similar content close to each other. Now I cannot reorder the attributes in the model when I make additional attributes.

**Comment by krukas** [comment] 2017-02-09 16:19
Ordering the snippet output is not possible, because each snippet doesn’t know about other snippets. Maybe we can add sort attribute to snippet class that points to a order param and sort by that before running

**Comment by krukas** [comment] 2017-09-04 17:43
Duplicate of #51

**Closed by krukas** 2017-09-04 17:43 UTC
Labels: enhancement
